config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'about/index'
  resources :questions do
    resources :answers, only: [:index, :new, :create]
  end
  resources :answers, only: [:show]

  resources :users

  resources :testimonials, only: [:index, :show, :new, :create]

  resource :about, only: [:index]


end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :question, presence: true
  validates :body, length: { minimum: 10 }, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers

  validates :description, :title, presence: true
  validates :title, length: { minimum: 10 }
  validates :description, length: { minimum: 15 }
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord


  validates :name, presence: true
  validates :body, presence: true



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true
  validates :email, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index

  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @question = Question.find(params[:question_id])
    @answers = @question.answers
  end

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.question = @question

    if @answer.save
      flash[:notice] = "Answer saved successfully."
      redirect_to question_path(@question)

    else
      flash[:alert] = "Failed to save question"
      render :new
    end
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      flash[:success] = 'Question successfully added!'
      redirect_to question_path(@question)
    else
      flash[:errors] = @question.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.update_attributes(question_params)
    if @question.save
      flash[:success] = 'Question successfully edited!'
      redirect_to question_path(@question)
    else
      flash[:errors] = @question.errors.full_messages.join(', ')
      render :new
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.answers.destroy_all
    @question.destroy
    flash[:success] = "Question Deleted"
    redirect_to questions_path(@question)
  end

  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  def index
    @testimonials = Testimonial.all
  end

  def new
    @testimonial = Testimonial.new
  end

  def create
    @testimonial = Testimonial.new(testimonial_params)

    if @testimonial.save
      flash[:success] = 'Testimonial successfully added!'
      redirect_to testimonial_path(@testimonial)
    else
      flash[:errors] = @testimonial.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
    @testimonial = Testimonial.find(params[:id])
  end

  def update
    @testimonial = Testimonial.find(params[:id])
    @testimonial.update_attributes(testimonial_params)
    if @testimonial.save
      flash[:success] = 'Testimonial successfully edited!'
      redirect_to testimonial_path(@testimonial)
    else
      flash[:errors] = @testimonial.errors.full_messages.join(', ')
      render :new
    end
  end

  def destroy
    @testimonial = Testimonial.find(params[:id])
    @testimonial.destroy_all
    @testimonial.destroy
    flash[:success] = "Testimonial Deleted"
    redirect_to testimonials_path(@testimonial)
  end

  def testimonial_params
    params.require(:testimonial).permit(:name, :body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = Users.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<!-- <div id="aboutContainer"> -->
  <%=image_tag("inca-jungle.jpg", class: "incaPhoto2") %>
  <div id="about_title2"><h1>Peru Dialogue of Civilization</h1></div>


		<div class="about_mona"><h3>Professor Canavan is a native of Peru <br>and a Professor of Spanish
			Studies<br> at Northeastern University.<br> Every summer she leads a new group<br> of students
			on a 5 week adventure <br>through the cities of Peru.<br> They experience the sights, history<br>
			 and culture of the country.</h3></div>

		<div class="about_border"><h3>The Peru Dialogue of Civilization is an amazing Spanish immersion
			program where students will speak Spanish, participate in cultural activities and
			interact with local people. It is an exciting way to explore the Spanish language and
			to experience another culture's people, ideas, customs and beliefs. Students will
			sample all that the cities of Lima, Ica and Cuzco have to offer using the Spanish
			language. Students will complete a Service Learning project (Air Force schools) in
			which they will help Peruvian high school students to practice speaking English and
			also explain the typical day in the life of a student at an American University.
			Students from Northeastern will participate in an immersion language program at the
			Private University UNIFE. The last week of the immersion program features a visit to
			the one of the seven wonders of the world,<br> MACHU PICCHU!</h3></div>


	<!-- </div> -->

app/views/answers/new.html.erb
<%=image_tag("aboutBG_2.jpg", class: "incaPhoto2") %>
<div class="question_border">
  <% unless @answer.errors.empty? %>
  <div>
    <%= @question.errors.full_messages.to_sentence %>
  </div>
<% end %>

<%= form_for [@question, @answer] do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

<p><%= link_to "Back", question_path(@question) %></p>

</div>

app/views/answers/show.html.erb
<h1> Answers: </h1>

app/views/home/index.html.erb
<div id="left">
  <%=image_tag("empty_cave_window2.png", id: "window") %>
  <%=image_tag("MACHU-PICCHU-facebook.jpg", id: "myPhotos") %>
</div>

<div id="right">
  <div id="welcomeAdventures">
  <%=image_tag("WelcomeAdventureText3.png")%>
  </div>

  <div id="torchLeft">
  <%=image_tag("LeftTorchesNoFlame350.png")%>
  </div>

  <div id="flame">
  <%=image_tag("LRflame0002.gif", style: "height:50%; width:50%;")%>
  </div>

  <div id="torchRight">
  <%=image_tag("RightTorchesNoFlame350.png")%>
  </div>

  <div id="flame2">
  <%=image_tag("LRflame0002.gif", style: "height:50%; width:50%;")%>
  </div>
</div>

</div>

</div>
</div>
<link rel="stylesheet" type="text/css"  href="PeruMona.scss">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Peru DOC</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="css/normalize.css">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  </head><div id ="wrapper">
<header class="BG" >
	<div >
    <!-- <img class="Map" src="images/PeruMap2.jpg"> -->
    <!-- <%=image_tag("PeruMap2.jpg", class: "Map") %> -->
    <%= link_to root_path do %>
      <%=image_tag("PeruDOC.png", class: "Peru") %>
    <% end %>
    	<!-- <a href="index.html"><img class="Peru" src="images/PeruDOC.png"></a> -->


      <%= link_to "https://www.northeastern.edu/", target: :_blank do %>
        <%= image_tag("neu-seal.png", id: :NU, alt: "Northeastern University") %>
      <% end %>


	<!-- <img id="NU" src="images/neu-seal.png"> -->


	<!-- <ul id="Icons"> -->
  <div class="row">
    <div class="links small-5 columns">


      <div>
        <% if current_user.present? %>
          <% if current_user.admin %>
            <%= link_to "Admin Page", users_path%>
          <%end%>
        <% end %>
      </div>
    </div>
    <div class="flashy small-4 columns centered-align">

        <% flash.each do |kind, message| %>
        <p><%= message %></p>
        <% end %>
    </div>
    <div class="text-right small-3 columns">
      <% if current_user.present? %>
        <% if current_user.avatar.present? %>
        <%= image_tag(current_user.avatar.url, size: "75x75", class: 'avatar_icon') %>
        <% else %>
        <%= image_tag("fallback/default.jpg", size: "75x75", class: 'avatar_icon') %>
        <% end %>
        <span><%= link_to current_user.username, user_path(current_user) %><span>
        <span><%= link_to "Log Out", destroy_user_session_path, :method => :delete %><span></br>
      <% else %>
        <p class= "loginbox"><%= link_to "Log In", new_user_session_path%>&nbsp&nbsp&nbsp&nbsp
        <%= link_to "Sign Up", new_user_registration_path%></p>
      <% end %>
    </div>
  </div>

      <%= link_to "https://www.facebook.com/PeruDialogueofCivilization/?fref=ts", target: :_blank do %>
        <%= image_tag("SocialMediaIcons/FacebookIcon.png", id: :FB, alt: "Facebook") %>
      <% end %>

      <%= link_to "https://twitter.com/perudialogue15", target: :_blank do %>
        <%= image_tag("SocialMediaIcons/TwitterIcon.png", id: :TW, alt: "Twitter") %>
      <% end %>

      <%= link_to "https://www.instagram.com/PeruDialogueofCivilization", target: :_blank do %>
        <%= image_tag("SocialMediaIcons/InstagramIcon.png", id: :IG, alt: "Instagram") %>
      <% end %>

      <!-- <%= link_to "http://indianajones.wikia.com/wiki/Peru", target: :_blank do %>
        <%= image_tag("idol_2.png", id: :IJ, alt: "Indiana Jones") %>
      <% end %> -->

			<!-- <li><a href="https://www.instagram.com/PeruDialogueofCivilization/?fref=ts" target="_blank">
			<img id="IG" src="images/SocialMediaIcons/InstagramIcon.png">
		    </a></li> -->
		<!-- </ul> -->

    </div>
</header>


	<div id="nav">
	  <ul>
      <div class="homebox">
        <%= link_to 'Home', root_path, :class => "button1" %>
        <%= link_to 'About', about_index_path, :class => "button2" %>
        <%= link_to 'Blog', href="http://perudocblog.com/", :class => "button3" %>
        <%= link_to 'Testimonials', testimonials_path, :class => "button4" %>
        <%= link_to 'Questions', questions_path, :class => "button5" %>
      </div>


		<!-- <li><a href="index.html"><img class="button1" src="homeButton.png"></a></li>
		<li><a href="about.html"><img class="button2" src="aboutButton.png"></a></li>
		<li><a href="http://perudocblog.com" target="_blank"><img class="button3" src="images/blogButton.png"></a></li>
		<li><a href="photos.html"><img class="button4" src="photosButton.png"></a></li>
		<li><a href="testimonials.html"><img class="button5" src="testimonialsButton.png"></a></li>
		<li><a href="contact.html"><img class="button6" src="contactButton.png"></a></li> -->
	  </ul>
	</div>


  <body>
    <!-- <div class="homebox">
      <%= link_to 'Home', root_path %>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      <%= link_to 'Blog', href="http://perudocblog.com/" %>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      <%= link_to 'Questions', questions_path %>
    </div> -->
    <div id="container">

  <%= yield %>

	<!-- <div id="left">
		<%=image_tag("empty_cave_window2.png", id: "window") %>
		<%=image_tag("MACHU-PICCHU-facebook.jpg", id: "myPhotos") %>
	</div>

	<div id="right">
		<div id="welcomeAdventures">
    <%=image_tag("WelcomeAdventureText3.png")%>
		</div>

		<div id="torchLeft">
		<%=image_tag("LeftTorchesNoFlame350.png")%>
		</div>

		<div id="flame">
		<%=image_tag("LRflame0002.gif", style: "height:50%; width:50%;")%>
		</div>

		<div id="torchRight">
		<%=image_tag("RightTorchesNoFlame350.png")%>
		</div>

		<div id="flame2">
		<%=image_tag("LRflame0002.gif", style: "height:50%; width:50%;")%>
		</div>
  </div>

	</div>

  </div>
</div>
<link rel="stylesheet" type="text/css"  href="PeruMona.scss"> -->


  </body>
</html>

app/views/questions/edit.html.erb
<%=image_tag("inca-jungle.jpg", class: "incaPhoto2") %>
<div id="title2"><h1>Edit Question</h1></div>

<div class="question_border">
<% unless @question.errors.empty? %>
  <div>
    <%= @question.errors.full_messages.to_sentence %>
  </div>
<% end %>

<%= form_for(@question) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div></br>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div></br>
<% end %>
</div>
<div class="edit_testimonial_border">
<p><%= link_to "Delete Question", @question, method: :delete, data: {confirm: "Are you sure?"} %></p>
<p><%= link_to "Back", questions_path %></p>
</div>

app/views/questions/index.html.erb
<!-- <h1 class="question1">Question</h1>
 -->

 <%=image_tag("aboutBG_2.jpg", class: "incaPhoto2") %>

<div class="questionlist">
  <ul>
  <% @questions.each do |question| %>
    <li> <%= link_to question.title, question_path(question)  %>  </li>
  <% end %>
</ul>
</div>

<br>

<div id="title2"><h1>Submit a Question</h1></div>

<div class="question_border">
  <h3>If you have any questions about the <br>Peru Dialogue of Civilization,
    feel <br>free to click the link below to ask <br>Professor Canavan a question.<br>
    She will reply pronto.</h3>
  <div class="cent">
  <p><%= link_to "Create New Question", new_question_path %></p>

    <p><%= link_to 'Back to Home', root_path %></p>

  </div>

</div>

app/views/questions/new.html.erb
<%=image_tag("aboutBG_2.jpg", class: "incaPhoto2") %>
<div id="title2"><h1> Submit a Question </h1></div>

<div class="question_border">
<% unless @question.errors.empty? %>
  <div>
    <%= @question.errors.full_messages.to_sentence %>
  </div>
<% end %>

<%= form_for(@question) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div><br>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description%>
  </div><br />

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<p><%= link_to "Back", questions_path %></p>

<div>

app/views/questions/show.html.erb
<%=image_tag("inca-jungle.jpg", class: "incaPhoto2") %>
<div id="title2"><h1> <%=@question.title%>  </h1></div>
<div class="question_border">

<h3><%=@question.description%></h3>

<p><%= link_to "Answer Question", new_question_answer_path(@question) %></p>

<p>
<ul>
  <% unless @answers.nil? %>
    <% @answers.each do |answer| %>
      <li> <%= answer.body %>  </li>
    <% end %>
  <% end %>
</ul>
</p>
</div>

<div class="edit_question_border">
<p><%= link_to "Edit Question", edit_question_path(@question) %></p>
<p><%= link_to "Delete Question", @question, method: :delete, data: {confirm: "Are you sure?"} %></p>
<p><%= link_to "Back", questions_path %></p>
</div>

app/views/static_pages/index.html.erb
<div id="app">
</div>

app/views/testimonials/index.html.erb
<!-- <h1 class="question1">Question</h1>
 -->

 <%=image_tag("aboutBG_2.jpg", class: "incaPhoto2") %>

<ul class="quest">
  <% @testimonials.each do |testimonial| %>

    <li> <%= link_to testimonial.name, testimonial_path(testimonial)  %>  </li>
  <% end %>
</ul>

<div id="title2"><h1>Write a Testimonial</h1></div>

<div class="question_border">
  <h3>If you have previously<br> participated in the <br>Peru Dialogue of Civilization, <br>
    please click the link below to share <br> your experience.<br>
    Thanks!</h3>
  <div class="cent">
  <p><%= link_to "Create New Testimonial", new_testimonial_path %></p>

    <p><%= link_to 'Back to Home', root_path %></p>

  </div>

</div>











	<!-- </div> -->

app/views/testimonials/new.html.erb
<%=image_tag("aboutBG_2.jpg", class: "incaPhoto2") %>
<div id="title2"><h1> Write a Testimonial </h1></div>

<div class="question_border">
<% unless @testimonial.errors.empty? %>
  <div>
    <%= @testimonial.errors.full_messages.to_sentence %>
  </div>
<% end %>

<%= form_for(@testimonial) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div><br>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<p><%= link_to "Back", testimonials_path %></p>

<div>

app/views/testimonials/show.html.erb
<h1><%=@testimonial.name%> </h1>
<h3><%=@testimonial.body%></h3>

<p><%= link_to "testimonial", new_testimonial_answer_path(@testimonial) %></p>
<p>

<ul>
  <% unless @testimonials.nil? %>
    <% @testimonials.each do |testimonial| %>
      <li> <%= testimonial.check_box(:best) testimonial.body %>  </li>
    <% end %>
  <% end %>
</ul>
</p>

<p><%= link_to "Edit Testimonial", edit_testimonial_path(@testimonial) %></p>
<p><%= link_to "Delete Testimonial", @testimonial, method: :delete, data: {confirm: "Are you sure?"} %></p>
<p><%= link_to "Back", testimonials_path %></p>











	</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
<%= link_to user.username, user_path(user)%>
    <%user.admin%>
<%end%>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>